### PR TITLE
fix CI errors && Support laravel 5.5

### PR DESCRIPTION
**Pull request by abr4xas**
- [x] Attempt to solve problems with continuous integration 
- [x] Removed support for php 5.6 by using PHPUnit `^6.4 `

### CODE REVIEW

**Comment by mbardelmeijer** [comment]
@mpociot any chance you could take look at this? Would be awesome to see this merged :)

**Comment by itsDamien** [comment]
please merge 😃

**Comment by AshPowell** [comment]
I think this package is abandoned... 9 months since last minor update and a year or so since any major updates

**Comment by daison12006013** [comment]
I guess we can't wait this to be merged @abr4xas, any plan to create your own cloned and registered packagist, making it as temporary until @mpociot have the time to merge this

**Comment by abr4xas** [comment]
@daison12006013 sure... :smiley:

**Comment by abr4xas** [comment]
@daison12006013 https://packagist.org/packages/abr4xas/onesignal

**Comment by nivanmorgan** [comment]
@abr4xas is it working.. this is the only package that is preventing me from update to laravel 5.5

**Comment by abr4xas** [comment]
@nivanmorgan yes, you can try it and see that it works by yourself

**Comment by daison12006013** [comment]
@abr4xas 

The previous `composer.json` was a minimum 5.3, I guess just add 5.5 in it instead of `5.*` which affects future Laravel 5.6 as well the <= 5.2

```
"illuminate/notifications": "5.3.*|5.4.*|5.5.*",
"illuminate/support": "5.1.*|5.2.*|5.3.*|5.4.*|5.5.*"
```

**Comment by abr4xas** [comment]
@daison12006013 

Yes, you are right. 
I thought that leaving it with 5. * would avoid repeating this process of waiting for them to update the package when there is a new version of laravel

**Comment by abr4xas** [comment]
I was thinking about working on a fork since the last update was 10 months ago.
@daison12006013 wanna join me?

**Comment by AshPowell** [comment]
Boom! Thank you @freekmurze

**Pull request merged**
