### PR TITLE
ability of user to send notification , filtering for multiple tags

### PR DESCRIPTION
**Pull request by rylxes**
the current notification sending by tags filtering 

`public function routeNotificationForOneSignal()
    {
        return ['tags' => ['key' => 'device_uuid', 'relation' => '=', 'value' => '123e4567-e89b-12d3-a456-426655440000']];
    }`

Ability to filter by more than one tag i.e
`public function routeNotificationForOneSignal()
    {
        return ['tags' =>
            [
                ['key' => 'device_uuid', 'relation' => '=', 'value' => '123e4567-e89b-12d3-a456-426655440000'],
                ['key' => 'role', 'relation' => '=', 'value' => 'admin']
            ]
        ];
    }`

### CODE REVIEW

**Comment by rylxes** [comment]
#73

**Comment by LKDevelopment** [comment]
Could you please rebase this on the refactor-to-traits branch?

**Comment by rylxes** [comment]
I have done that, ... the current branch is up to date

**Comment by LKDevelopment** [comment]
For me this looks okay @Lloople what do you think?

**Pull request merged**
