### PR TITLE
Support for 5.5

### PR DESCRIPTION
**Pull request by jpmurray**
Updated packages for 5.5 support, and added required lines for package auto-discovery.

Also made some small cosmetic change to the readme so it's clear that the package supports laravel >= 5.3.

### CODE REVIEW

**Comment by J0sh0nat0r** [comment]
@mpociot Any idea if / when this will be merged since 5.5 is released now?

**Comment by 0plus1** [comment]
Is anybody actually taking care of this PR? Should I make one myself?

**Comment by jpmurray** [comment]
I'm just not sure what exactly is failing in travis-ci here. Says Test case doesn't work, but it's forked from current master branch?

**Comment by ianrothmann** [comment]
It seems like the error is Class 'PHPUnit_Framework_TestCase' not found when testing?

**Comment by 0plus1** [comment]
This occurs because PHPUnit 6 which is the new dependency of Laravel 5.5, is now namespaced:

https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1

You will need to refactor things like \PHPUnit_Framework_TestCase to \PHPUnit\Framework\TestCase

**Comment by jpmurray** [comment]
OH! Good catch, I'll go change that in the coming minutes / hour.

**Comment by jpmurray** [comment]
I'm not waiting for the tests to finish, but locally I'm hitting a trouble with the fact that some tests do not do any assertions. I wanted to make it quick, but I don't really have the time to go over the tests to rethink them, so if anyone wants to fork my fork and build on it so we can go on, please do!

**Comment by dominikkukacka** [comment]
Hi there, any news on the merge? :)

**Comment by sagargulati** [comment]
@laravel-notification-channels any update on PR?

**Comment by ramonvic** [comment]
any news on this?

**Comment by ianrothmann** [comment]
I've made a fork while we wait for this problem to resolve. I renamed the namespace in the fork just for it to be obvious that I'm still using the forked version.

In composer.json add the following:

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/ianrothmann/onesignal"
        }
    ],

and
 "require":{
       "ianrothmann/onesignal": "dev-master",
}

I've got it in production with L5.5 and it works just fine.

**Comment by AshPowell** [comment]
@@laravel-notification-channels ... A lot of people waiting on this... any update?

**Comment by abhimanyu003** [comment]
We really need an update on laravel 5.5 support.

**Comment by victorhugorch** [comment]
Please, accept this PR.

**Comment by sbahr001** [comment]
Any updates?

**Comment by jpmurray** [comment]
Ok people, seriously, if there was any update, there would be news on this PR, don't you think?

**Comment by kaankilic** [comment]
bump up for the merge. Currently, waiting for this update.

**Comment by sagargulati** [comment]
Still falling, please check @laravel-notification-channels
Any more updates?

**Pull request closed without merging**
