### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^9.3`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/onesignal.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravel-notification-channels/onesignal": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by lkmadushan** [comment]
@mpociot any update about the release date of Laravel 9 support?

**Comment by faytekin** [comment]
If you send notifications only with OneSignal Player ID, the [macellan/onesignal](https://github.com/macellan/onesignal) package has Laravel 9 compatibility.

**Comment by AshPowell** [comment]
@LKaemmerling @mpociot any eta on the merge?

Thanks

**Comment by cbaconnier** [comment]
Tests are passing, but I believe using this PR will currently fail since it depends on this PR that is also not merged https://github.com/berkayk/laravel-onesignal/pull/159

**Comment by innocenzi** [comment]
> I believe using this PR will currently fail since it depends on this PR that is also not merged [berkayk/laravel-onesignal#159](https://github.com/berkayk/laravel-onesignal/pull/159)

This one should be merged instead, https://github.com/berkayk/laravel-onesignal/pull/162, since the one you linked didn't include Guzzle updates - but yes you're right, this PR should be merged after support for L9 is added to `berkayk/laravel-onesignal`

**Comment by MatheusNascimentoti99** [comment]
When will accept the pull request?

**Comment by MatheusNascimentoti99** [comment]
When will you accept the pull request?

**Comment by mweghorst** [comment]
Laravel 9 support has now been added to `berkayk/onesignal-laravel`

**Comment by innocenzi** [comment]
Would be really nice if a maintainer could merge this, now that nothing is blocking this PR. 🙏 

cc @LKaemmerling @mpociot

**Comment by MatheusNascimentoti99** [comment]
When will merge it?

**Comment by rafaellaurindo** [comment]
Any updates?

**Comment by innocenzi** [comment]
FYI, in the meantime, one can use Shift's fork (<3): https://github.com/laravel-notification-channels/onesignal/pull/137#issuecomment-1030829377. It works now that the underlying PR has been merged too.

Please do not spam the issue, this won't help getting it merged. We just have to wait now.

**Comment by AshPowell** [comment]
> Sorry guys, i didn't got any notification for this repo for whatever reason.

Cheers Lukas

**Pull request merged**
