### PR TITLE
Allow Laravel 6

### PR DESCRIPTION
**Pull request by AshPowell**

### CODE REVIEW

**Comment by Lloople** [comment]
Thank you for your PR!

PHPUnit and Testbench should be updated too

@LKaemmerling Could you please take a look into this and make sure everything is right? 🙏

**Comment by AshPowell** [comment]
> Thank you for your PR!
> 
> PHPUnit and Testbench should be updated too
> 
> @LKaemmerling Could you please take a look into this and make sure everything is right? 🙏

Yep completely didn't think!, Sorry for closing too just saw the notification and assumed a separate, complete pull request was created.

**Comment by AshPowell** [comment]
@LKaemmerling just in case you missed it 😀

**Comment by LKaemmerling** [comment]
Actually i see the tests are failing. Could you please remove php 7.0 ? I guess we can release this than as the final 2.0

**Comment by LKaemmerling** [comment]
@AshPowell @Lloople could you look over this again? I have fixed the phpunit tests.

**Comment by AshPowell** [comment]
With the checks being removed for older php versions, should v2 also require php ^7.2?

**Comment by Lloople** [comment]
Looks good to me 👍 Only regarding thing is the matter @AshPowell said about backward compatibility.

**Comment by LKaemmerling** [comment]
Let's wait on travis, then i guess we can release this :)

**Pull request merged**
