### PR TITLE
minimalistic silent push notification support

### PR DESCRIPTION
**Pull request by kjostling**
Made a small change to enable sending push notifications without body and subject (ie silent push notifications). Also forced the content_available parameter, if data is set, but Im not sure if thats needed since I could use "setParameter" to do that. 

The "real" implementation should probably be to add a "setSilent" method and adjust the payload accordingly. 

Good enough?

### CODE REVIEW

**Comment by LKDevelopment** [comment]
It doesn't make sense to me, to sent a notification to a user without any content... @Lloople what do you think?

**Comment by AshPowell** [comment]
@LKDevelopment they've already consented to receiving notifications, though this doesn't inform them of anything as its not actually a notification - its more just waking the device so the app can run background updates etc

**Comment by Lloople** [comment]
It doesn’t make sense to me either. Maybe it’s better to have a method for silent notifications instead of adding code to this one.

**Comment by LKDevelopment** [comment]
Yeah this would be acceptable for me @kjostling could you please do this on the refactor-to-traits branch (and add tests for this case?)

**Comment by kjostling** [comment]
I can have a look at that sure. 
The use case for silent push notifications is to trigger app functions in background as mentioned by @AshPowell

**Comment by kjostling** [comment]
Refactored here, hope I got it right. 
https://github.com/laravel-notification-channels/onesignal/pull/67

**Pull request closed without merging**
